name: ci

on:
  push:
    branches: [master]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  pull_request:

jobs:
  pre-commit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - uses: pre-commit/action@v2.0.0

  tests:

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        sphinx: [">=4,<5"]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            python-version: "3.8"
            sphinx: ">=3,<4"
          - os: windows-latest
            python-version: "3.8"
            sphinx: ">=4,<5"

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[develop]
        pip install --upgrade-strategy "only-if-needed" "sphinx${{ matrix.sphinx }}"
    - name: Run pytest
      run: |
        pytest --cov=sphinx_glossary --cov-report=xml --cov-report=term-missing
        coverage xml
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1
      with:
        name: sphinx-glossary
        flags: pytests
        file: ./coverage.xml
        fail_ci_if_error: true

  # publish:

  #   name: Publish to PyPi
  #   needs: [pre-commit, tests]
  #   if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout source
  #     uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: "3.8"
  #   - name: install flit
  #     run: pip install flit~=3.2
  #   - name: Build and publish
  #     run: flit publish
  #     env:
  #       FLIT_USERNAME: __token__
  #       FLIT_PASSWORD: ${{ secrets.PYPI_KEY }}
